version: "3.8"

services:
  # Сервис для PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: generator_db
    ports:
      - "5431:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис для ASP.NET приложения
  web:
    image: myaspnetcontainer
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Проброс порта для веб-приложения
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS = 7108
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=1111;Database=generator_db
    depends_on:
      - postgres
    networks:
      - app_network

  # Сервис для фронтенда
  frontend:
    image: frontend
    build:
      context: ./client-generator
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network


  # Сервис для pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:8081"  # Доступ к pgAdmin через браузер по адресу http://localhost:5050
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

